Repository tuning-8/swe-sose2022_exam-repository, pull requests merged in 2022-07, with the labels that each got.

#4 Basic class structure
  OpenMensa_Parser/OpenMensa_Parser/HtmlParser.cs
  OpenMensa_Parser/OpenMensa_Parser/Menu.cs
  OpenMensa_Parser/OpenMensa_Parser/Parser.cs
  OpenMensa_Parser/OpenMensa_Parser/Program.cs
  OpenMensa_Parser/OpenMensa_Parser/TxtReader.cs
  OpenMensa_Parser/OpenMensa_Parser/XmlWriter.cs
Labels: enhancement

#10 Implemented the 'HtmlParser' class
  OpenMensa_Parser/OpenMensa_Parser/HtmlParser.cs
  OpenMensa_Parser/OpenMensa_Parser/Menu.cs
  OpenMensa_Parser/OpenMensa_Parser/Parser.cs
  OpenMensa_Parser/OpenMensa_Parser/TxtReader.cs
Labels: enhancement

#12 Implemented the 'TranslateIngredients' class
  OpenMensa_Parser/OpenMensa_Parser/IngredientsTranslator.cs
Labels: enhancement

#11 Implemented the 'XmlWriter' class
  OpenMensa_Parser/OpenMensa_Parser/XmlWriter.cs
Labels: enhancement

#15 Implemented the menu-information classes
  OpenMensa_Parser/OpenMensa_Parser/HtmlParser.cs
  OpenMensa_Parser/OpenMensa_Parser/Menu.cs
  OpenMensa_Parser/OpenMensa_Parser/Parser.cs
Labels: enhancement

#19 Functionality testing
  .gitignore
  OpenMensa_Parser/OpenMensa_Parser/IngredientsTranslator.cs
  OpenMensa_Parser/OpenMensa_Parser/Parser.cs
  OpenMensa_Parser/OpenMensa_Parser/XmlWriter.cs
Labels: test

#20 Added doxygen compatible comments
  .gitignore
  OpenMensa_Parser/OpenMensa_Parser/HtmlParser.cs
  OpenMensa_Parser/OpenMensa_Parser/IngredientsTranslator.cs
  OpenMensa_Parser/OpenMensa_Parser/Menu.cs
  OpenMensa_Parser/OpenMensa_Parser/Parser.cs
  OpenMensa_Parser/OpenMensa_Parser/XmlWriter.cs
Labels: documentation
